name: Python code coverage
on:
  schedule:
    - cron: '0 12 * * 1,4'
  workflow_call: {}

jobs:
  code_coverage:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Step 1 - Collect coverage
        run: |
            python3 -V
            pyvenv venv
            source venv/bin/activate
            python3 -m pip install coverage
            python3 -m coverage run --omit=functional_test.py,unit_test.py -m unittest discover -p '*_test.py'
            python3 -m coverage html
      - name: Step 2 - Use upload artifact actions
        uses: actions/upload-artifact@v3
        with:
          name: Coverage result
          path: ./htmlcov
